### ISSUE TITLE
Error in args[12]

### ISSUE THREAD

**Issue by chadi-elfarran** [WGLab/w4CSeq#1]
Greetings to you.

Thank you for creating this extremely useful tool.

I am using the 4C_enzyme_cmdline.R to do the analysis. The tool runs smoothly until it merges the bam files and creates the UCSC_view.bed. The following error appears:

**Error in args[12] : object of type 'closure' is not subsettable
Calls: system -> paste**

I think the error is coming from this part of the code:
**system(paste("sed -i '1s/^/browser position ", bait_ch, ":", as.numeric(bait_st)-10000, "-", as.numeric(bait_en)+10000, "\nbrowser hide all\nbrowser pack refGene encodeRegions\ntrack type=bedGraph name=\"4C signal (raw reads) (", args[12], ")\" description=\"4C read counts\" db=", build, " visibility=2 color=0,0,0 useScore=1 alwaysZero=on\n/' UCSC_view.bed", sep=""))**

Can you kindly help me rectify this error.

Thank you

**Comment by nuoyazhou2** [comment]
Hi,

The error is fixed now, with code updated. Please download the latest
version, or you can substitute the "args[12]" to "exp_name" in your local
4C_enzyme_cmdline.R code. Thanks a lot for your information.

Best.

**Comment by chadi-elfarran** [comment]
Hi nuoyazhou2,

Thank you for your reply and all the effort. The pipeline is now working smoothly. I had to do the following additional steps (after downloading the latest version) to make it work completely:

1- I had to change the header in the file "count_sites_binomial.pl" into **"#!/usr/bin/perl"**.

2- I had to change the path in line 6 of the "count_sites_binomial.pl" into the directory in which perl modules are installed.

3- I had to download the "cytoBands.txt.gz" manually from UCSC and place it in the corresponding lib folder.

It will be great if these issues could be rectified in the code itself or by noting the users in the documentation. 

I would like to thank you once again for all the effort in creating this helpful tool for analyzing 4C-Seq data.

Best Regards,

**Comment by nuoyazhou2** [comment]
Hi Chadi-elfarran,

Thanks a lot for your feedback. We have now added in the documentation,
noting users to specify the interpreter and module directory (as different
users might have their own interpreters and modules directories).

As for the 3rd point, you don't need to download the "cytoBands.txt.gz". We
use function from R package "quantsmooth", which automatically includes the
cytobands info for _hg19/hg18/mm10_. We have added "cytoBands.txt.gz" for
_mm9_ manually. So you don't have to download files manually yourself.

Thanks a lot for helping us improve the tool.

Best regards,

**Comment by tamerawwad** [comment]
Hi nuoyazhou2,
 i am trying to run the code but sonehow it gives me an error message when running the following command:
```
if (grepl("^chr(\\d{1,2}|X|Y)$", bait_ch)) {
    system(paste("sed -i '1s/^/browser position", bait_ch, ":", as.numeric(bait_st)-10000, "-", as.numeric(bait_en)+10000, "\\nbrowser hide all\\nbrowser pack refGene encodeRegions\\ntrack type=bedGraph name=\"4C signal (raw reads) (", exp_name, ")\" description=\"4C read counts\" db=", build, " visibility=2 color=0,0,0 useScore=1 alwaysZero=on\\n/' UCSC_view.bed", sep=""))
} else {
    system(paste("sed -i '1s/^/browser position", "chr1", ":1-10000000\\nbrowser hide all\\nbrowser pack refGene encodeRegions\\ntrack type=bedGraph name=\"4C signal (raw reads) (", exp_name, ")\" description=\"4C read counts\" db=", build, " visibility=2 color=0,0,0 useScore=1 alwaysZero=on\\n/' UCSC_view.bed", sep=""))    
}
```
the error message says:
sed: 1: "UCSC_view.bed": invalid command code U

what could possibly be wrong?
many many thanks
Tamer
