### ISSUE TITLE
Samtools compatibility

### ISSUE THREAD

**Issue by chadi-elfarran** [WGLab/w4CSeq#2]
Dear Admin,
Greetings to you.

In new samtools version, the sort command has changed to:
samtools sort -o enzyme_sorted.bam bam_file.

So I had to change line 60 in 4c_enzyme_cmdline.R and line 84 in 4c_enzyme.R to the following:
system(paste(path_samtools, "/samtools sort -o enzyme_sort.bam", " ", file_bam, sep=""))

After that the run seems fine.

Just wanted to confirm if this is alright for the function of the code?

Best Regards,

Chadi

**Comment by kaichop** [comment]
Looks okay
