### ISSUE TITLE
 "paired-end data " option in Enzyme-digestion based analysis

### ISSUE THREAD

**Issue by zhaocheng3326** [WGLab/w4CSeq#3]
In enzyme_config.r, there is an option of "file_in: path to the raw fastq file".
 However , in sonication_config.r, there are option of "file_in1: path to the paired end raw fastq files #1" and 
"file_in2: path to the paired end raw fastq files #2".
Is it meaning that we can only use 4C_enzyme_cmdline.R to analysis single-end data and use 4C_sonication_cmdline.R for paired-end data ?

**Comment by nuoyazhou2** [comment]
Yes. The tool analyzes single-end enzyme digestion based 4C-Seq data and
paired-end sonication based 4C-Seq data.

**Comment by zhaocheng3326** [comment]
If  I have 4C-Seq data which is paired-end and also made by enzyme-digestion. Is it ok to use 4C_sonication_cmdline.R to analysis it ?

**Comment by nuoyazhou2** [comment]
No. The current framework only supports analysis of single-end enzyme
digestion based 4C-Seq data.
