### ISSUE TITLE
Replicates and annotation files

### ISSUE THREAD

**Issue by aliu90** [WGLab/w4CSeq#4]
Hi,

I was wondering if there is any way for this software to analyze replicates or compare significant interactions across different samples? And another question, in your paper, there is mentioned an optional module where users can upload a BED formatted annotation file, such as ChIP-seq peaks. Is this available for command line enzyme based digestion?

Thank you.

**Comment by nuoyazhou2** [comment]
Hello,

At this point, the tool can only analyze individual dataset. If you want to
compare between replicates or across samples, it is recommended to take
advantage of intermediate files containing the window-based counts and use
differential analysis tool such as DESeq2 to analyze the data.

Yes, the BED formatted annotation files can be specified in the command
line file, by specifying the path to the control file (if any) to chipc,
and paths to files of the experiment to chip1, chip2, chip3, etc.

**Comment by aliu90** [comment]
Hi I'm still having trouble getting the Chip-Seq enrichment analysis to work. 

I downloaded a ChIP-seq dataset from UCSC. It's the bed file for peaks (I'm not sure if this is the right file type or maybe I have to modify this file in some way). 

I have no control dataset, so the only modification to the R script I made is here: 

if (control == "no") {
                chipfile <- c("H3K4me3.bed")

And I have this bed file in my working directory. 

This is the error message I'm getting:
Error in if (chipdata == "yes" && file.info("chip_name.txt")$size > 0) { :
  missing value where TRUE/FALSE needed
Execution halted

I'd really appreciate any advice you can give to solve this problem.

**Comment by nuoyazhou2** [comment]
Please try the following and then run the script.

1) On line #17 of 4C_enzymecmdline.R, change chipdata <- "no" to chipdata <-
"yes"
2) On line #18, add chip1 <- "H3K4me3" #no .bed suffix
    You also need to revert the change you have done. So change
if (control == "no") {
chipfile <- c("H3K4me3.bed")

back to original.
3) Create a file named chip_name.txt, and then put string H3K4me3 into it.

**Comment by aliu90** [comment]
I did the changes and I'm still getting the same error message. 
The file I created chip_name.txt is in my working directory. Do I need to read it into the script or does the script already know to open it?

**Comment by aliu90** [comment]
After a few runs, I think the script finally recognizes my chip file. I'm getting a different error message now:

Error in boxplot.default(chip_frame, col = c("red", "grey"), at = setdiff(1:(3 *  :
  invalid first argument
Calls: boxplot -> boxplot.default
Execution halted

I don't think it likes my chip input file. Is this not the type of file I should be using?

<img width="793" alt="screen shot 2017-10-30 at 12 23 39 am" src="https://user-images.githubusercontent.com/26095513/32154684-9a118c5a-bd08-11e7-8525-0130c137adf5.png">

**Comment by nuoyazhou2** [comment]
Please delete the first column of your ChIP file, as only bed file is
accepted. In addition, you might want to comment out the header line or
delete it simply.

**Comment by aliu90** [comment]
I'm still getting the following error:  Error in boxplot.default(chip_frame, col = c("red", "grey"), at = setdiff(1:(3 *  : 
  invalid first argument

I ran the code line by line and immediately after:
> system(paste("sort -R ", enzyme_genome, " | awk '$1 != \"chrY\"' | head -n 100000 | sort -k1,1 -k2,2n > enzyme_genome_100k.bedsort0", sep=""))

I get this message, which I think may be why it's failing. 
sort: write failed: 'standard output': Broken pipe
sort: write error

Any idea how to fix this? I have included the script and file I'm working with.

[chip_name.txt](https://github.com/WGLab/w4CSeq/files/1438907/chip_name.txt)
[chipseq_enrichment.txt](https://github.com/WGLab/w4CSeq/files/1438909/chipseq_enrichment.txt)

**Comment by nuoyazhou2** [comment]
The following line is not the reason for the error. (Whenever sort doesn't
write all its output, it reports the "Broken pipe" message, which can be
ignored in this case.)
system(paste("sort -R ", enzyme_genome, " | awk '$1 != "chrY"' | head -n
100000 | sort -k1,1 -k2,2n > enzyme_genome_100k.bedsort0", sep=""))

The reason for error is shown here.
Error in boxplot.default(chip_frame, col = c("red", "grey"), at =
setdiff(1:(3 * :
which suggests your chip_frame might be empty.

As you have modified the code, you need to make sure your changes are
consistent throughout your code. Please find this line, chipfile <-
c("chip1", "chip2", "chip3", "chip4", "chip5", "chip6", "chip7", "chip8",
"chip9", "chip10"), and delete the double quotation marks. By that I mean
you change it to chipfile <- c(chip1, chip2, chip3, chip4, chip5, chip6,
chip7, chip8, chip9, chip10). (These are variables to which you have
assigned values in the first a few lines in your code.)

**Comment by aliu90** [comment]
The code seems to be working now, I got a pdf image to print properly. Unfortunately, beyond the axes, title, and labels, the actual data part is completely blank. I have attached the txt files created by the Rscript. The last columns are entirely zeros. I don't think this should be the case. Is there something I should be changing in my ChIP-seq input bed file?

[CTCF_rand.txt](https://github.com/WGLab/w4CSeq/files/1522740/CTCF_rand.txt)
[CTCF.txt](https://github.com/WGLab/w4CSeq/files/1522741/CTCF.txt)

**Comment by nuoyazhou2** [comment]
The last columns in your files are not all zeros, but most of them are very
small numbers. That indicates that CTCF doesn't have much enrichment around
your 4C sites. You may want to increase the window size for windowBed and
change ylim=c(-45,45) to customize your small number of enrichments.

**Comment by aliu90** [comment]
I'm not sure how to increase the window size for windowBed, also ylim is already set to c(-45,45).

Could there be something wrong with my input bed files? I'm a bit surprised by the low enrichment across so many different ChIP-seq datasets. The output pdf is just blank. Wouldn't I at least see something for "Random sites"?

[CTCF_bedinput.txt](https://github.com/WGLab/w4CSeq/files/1525135/CTCF_bedinput.txt)
[ChIP-Seq.pdf](https://github.com/WGLab/w4CSeq/files/1525136/ChIP-Seq.pdf)

**Comment by nuoyazhou2** [comment]
From the plot, you can see it's not blank. Rather, the boxes are "squeezed"
around zero, due to low enrichment level of factors around your 4C sites.
To address that, you need to increase the window size for windowBed by
adjusting the "-c" parameter. Take a look at this.
http://bedtools.readthedocs.io/en/latest/content/tools/window.html

On the other hand, to show the full range of the boxplot, you'd better
narrow down the ylim from c(-45, 45) to a smaller range like c(-10,10).
