### ISSUE TITLE
install w4CSeq

### ISSUE THREAD

**Issue by DittmanC** [WGLab/w4CSeq#8]
I was trying to install w4CSeq via git clone git@github.com:WGLab/w4CSeq.git. It shows permission denied for downloading it. 
Cloning into 'w4CSeq'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by kaichop** [comment]
Generally speaking, you need to add your ssh key to your github account (so github knows who you are), to use "git@github.com" to download. See https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
